#!/usr/bin/env python3
"""Pull GitHub repo traffic stats (clones + views) and append to history.

GitHub's traffic API only surfaces the last 14 days, so the only way to keep
a long-term record is to poll periodically and merge into a checked-in
history file. Run this locally at least once every 14 days with the user token
returned by ``gh auth token``; the default GitHub Actions token cannot access
repository traffic for this project.

Inputs (env vars):
    GH_TOKEN   GitHub user token with read access to the repo's traffic;
               ``gh auth token`` supplies the expected value.
    OWNER      Repo owner, e.g. "Arcadia-1"
    REPO       Repo name,  e.g. "virtuoso-bridge-lite"

Outputs (written under stats/):
    clones.json   {"<YYYY-MM-DD>": {"count": N, "uniques": K}, ...}
    views.json    same shape
    README.md     human-readable last-30-days summary, regenerated each run
"""

from __future__ import annotations

import json
import os
import sys
import urllib.request
import urllib.error
from datetime import datetime, timezone
from pathlib import Path

API_BASE = "https://api.github.com"
STATS_DIR = Path(__file__).resolve().parent.parent / "stats"


def _get(url: str, token: str) -> dict:
    req = urllib.request.Request(
        url,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "vb-traffic-tracker",
        },
    )
    with urllib.request.urlopen(req, timeout=20) as resp:
        return json.loads(resp.read().decode("utf-8"))


def _load_history(path: Path) -> dict[str, dict[str, int]]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def _save_history(path: Path, history: dict[str, dict[str, int]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    # Sort by date for readable diffs in PRs
    sorted_history = dict(sorted(history.items()))
    path.write_text(
        json.dumps(sorted_history, indent=2) + "\n",
        encoding="utf-8",
    )


def _merge(history: dict, payload: dict) -> dict:
    """Merge GitHub's 14-day window into long-term history.

    Each entry in payload['clones'] / payload['views'] looks like:
        {"timestamp": "2026-04-29T00:00:00Z", "count": 5, "uniques": 3}

    For a date already present in history, GitHub's number wins (it's the
    authoritative same-day total; our previous poll may have caught a
    partial day).  Older days that have already aged out of the 14-day
    window remain untouched.
    """
    series = payload.get("clones") or payload.get("views") or []
    for entry in series:
        ts = entry.get("timestamp", "")[:10]
        if not ts:
            continue
        history[ts] = {
            "count": int(entry.get("count", 0)),
            "uniques": int(entry.get("uniques", 0)),
        }
    return history


def _render_readme(
    clones: dict[str, dict[str, int]],
    views: dict[str, dict[str, int]],
    owner: str,
    repo: str,
) -> str:
    """Render a markdown summary of the last 30 calendar days."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    last30_clones = sorted(clones.items())[-30:]
    last30_views = sorted(views.items())[-30:]

    def _table(rows: list[tuple[str, dict[str, int]]], title: str) -> str:
        # Daily ``unique`` column kept because each entry is GitHub's
        # authoritative single-day distinct-cloner count.  We do NOT sum
        # this column anywhere -- summing across days double-counts
        # cloners who returned, which over-estimates the rolling-window
        # set-unique that GitHub itself reports.
        lines = [
            f"### {title}",
            "",
            "| Date | Total | Unique that day |",
            "|---|---:|---:|",
        ]
        if not rows:
            lines.append("| (no data yet) | | |")
        for date, v in rows:
            lines.append(f"| {date} | {v['count']} | {v['uniques']} |")
        return "\n".join(lines)

    clones_total = sum(v["count"] for v in clones.values())
    views_total  = sum(v["count"] for v in views.values())

    return "\n".join([
        f"# `{owner}/{repo}` Traffic",
        "",
        f"_Auto-generated by `scripts/track_traffic.py` on {now}._",
        "",
        f"GitHub's Traffic API only exposes the last 14 days; this directory",
        f"keeps a long-term archive updated by periodic local polling.",
        "",
        "## Lifetime totals (in tracked window)",
        "",
        f"- **Clones:** {clones_total}",
        f"- **Views:**  {views_total}",
        "",
        "_Only `count` totals are reported.  Per-day unique cloners /",
        "viewers are kept in the daily tables but **not summed** -- a",
        "cloner who returns on N different days would be counted N",
        "times, over-stating the real distinct-cloner population that",
        "GitHub itself reports as a 14-day rolling set._",
        "",
        _table(last30_clones, "Last 30 days — Clones"),
        "",
        _table(last30_views, "Last 30 days — Views"),
        "",
    ])


def main() -> int:
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    owner = os.environ.get("OWNER")
    repo = os.environ.get("REPO")
    if not (token and owner and repo):
        print("missing env: GH_TOKEN / OWNER / REPO", file=sys.stderr)
        return 2

    STATS_DIR.mkdir(parents=True, exist_ok=True)

    clones_path = STATS_DIR / "clones.json"
    views_path = STATS_DIR / "views.json"

    clones = _load_history(clones_path)
    views = _load_history(views_path)

    try:
        clones = _merge(
            clones,
            _get(f"{API_BASE}/repos/{owner}/{repo}/traffic/clones", token),
        )
        views = _merge(
            views,
            _get(f"{API_BASE}/repos/{owner}/{repo}/traffic/views", token),
        )
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")[:200]
        print(f"GitHub API error {exc.code}: {body}", file=sys.stderr)
        # Traffic endpoints need push/admin access. The default Actions
        # GITHUB_TOKEN is insufficient; use the user token from `gh auth token`.
        return 1

    _save_history(clones_path, clones)
    _save_history(views_path, views)

    (STATS_DIR / "README.md").write_text(
        _render_readme(clones, views, owner, repo),
        encoding="utf-8",
    )

    # Shields.io endpoint badges -- consumed by README.md via
    # https://img.shields.io/endpoint?url=<raw URL>.  Schema:
    # https://shields.io/endpoint
    #
    # Only the ``count`` totals are surfaced.  Daily-unique sums are
    # deliberately omitted because cross-day sums double-count cloners
    # who return on multiple days, over-stating the real distinct
    # population (GitHub reports that as a 14-day rolling SET, not
    # something we can reconstruct from daily numbers post-hoc).
    def _badge(label: str, total: int, color: str) -> dict:
        return {
            "schemaVersion": 1,
            "label": label,
            "message": str(total),
            "color": color,
            # 5-minute cache: short enough that schema/format edits to
            # this script propagate to the user-visible badge within
            # the next page load, long enough not to thrash shields.io
            # for a metric updated only by periodic local polling.
            "cacheSeconds": 300,
        }

    clones_total = sum(v["count"] for v in clones.values())
    views_total  = sum(v["count"] for v in views.values())

    (STATS_DIR / "clones-badge.json").write_text(
        json.dumps(_badge("clones", clones_total, "blue")) + "\n",
        encoding="utf-8",
    )
    (STATS_DIR / "views-badge.json").write_text(
        json.dumps(_badge("views",  views_total,  "green")) + "\n",
        encoding="utf-8",
    )

    print(f"clones tracked: {len(clones)} day(s)")
    print(f"views  tracked: {len(views)} day(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
